CREATE TABLE perfis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    nomecompleto VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    altura DOUBLE,
    peso DOUBLE,
    nascimento VARCHAR(12) NOT NULL,
    bio TEXT,
    ativo BOOLEAN,
    celular VARCHAR(20),
    fixo VARCHAR(20),
    recado VARCHAR(20),
    whatsapp VARCHAR(20),
    logradouro VARCHAR(255),
    bairro VARCHAR(255),
    cep VARCHAR(20),
    numero VARCHAR(20),
    complemento VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(2)
);
